### PR TITLE
Allow strobe on any GPIO

### PR DESCRIPTION
**Pull request by servos**
This PR allows the camera to be configured to use any of the GPIO pins as the strobe pin.

### CODE REVIEW

**Comment by efernandez** [comment]
This is almost the same as https://github.com/ros-drivers/pointgrey_camera_driver/pull/80, isn't it?

**Comment by servos** [comment]
Yes it is pretty much the exact same. There seems to be some debate about getting that committed upstream so we should still push it here. I can change this to a cheery-pick of that commit if you think that is better.

**Comment by servos** [comment]
I'd like to merge this today so I can test it in the bundle.

**Comment by mikepurvis** [comment]
LGTM to me, and it'll be compatible with the upstream change when that goes in.

**Comment by efernandez** [comment]
They're almost the same. So I'll merge this one so we can test it.

**Pull request merged**
